### ISSUE TITLE
Error on getVersion()

### ISSUE THREAD

**Issue by gambledor** [lorislab/semver-release-maven-plugin#2]
java version: openjdk 8
mvn version: 3.6.3
os: archlinux
plugin release: 0.6.0-SNAPSHOT

Whatever maven goal I run I'll get the following error:

apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.lorislab.maven:semver-release-maven-plugin:0.6.0-SNAPSHOT:version-git-hash (default-cli) on project semver-demo: Execution default-cli of goal org.lorislab.maven:semver-release-maven-plugin:0.6.0-SNAPSHOT:version-git-hash failed.

**Comment by andrejpetras** [comment]
@gambledor thank you for reporting this issue
Do you have example `pom.xml` project file for me, where I can reproduce this issue?

**Comment by gambledor** [comment]
@andrejpetras thank you for replying.
After viewing the source code I understood what was the problem.
My version tag was something like 1.0-SNAPSHOT but it must be something like 1.0.0-SNAPSHOT.
In this very last way it's recognized as a valid string version and updated accordingly.

**Comment by andrejpetras** [comment]
@gambledor 
thanks for the PR. I will create a new release.

I'm also adding this error log for more information if this error occurs again:
```
[INFO] --- semver-release-maven-plugin:0.7.0:version-git-hash (default-cli) @ release-notes ---
[ERROR] Only the SemVer 2.0 format (major.minor.patch-label) is supported for the project version!
[ERROR] Error parsing version: 1.0-SNAPSHOT, error:Unexpected character 'HYPHEN(-)' at position '3', expecting '[DOT]'

```
